### ISSUE TITLE
想和你一起开发象棋ai，不知道您意见如何？

### ISSUE THREAD

**Issue by Ways49** [Yesdevelop/ChineseChess#1]
我自己也写过象棋ai，对这方面也很感兴趣，想从头构建一个象棋程序，但是一个人又力不从心。

**Comment by Yesdevelop** [comment]
很高兴有了一个合作伙伴。这是我用C++写的一个

**Comment by Foryesify** [comment]
非常高兴能在开发的道路上碰见一个志同道合的人

**Comment by Ways49** [comment]
那我应该怎么联系您呢？

**Comment by Ways49** [comment]
如果合作开发ai的话，只提issue肯定不太行吧

**Comment by Foryesify** [comment]
QQ: 2820795095，邮箱：yes-noob@outlook.com

**Comment by Foryesify** [comment]
今天在看历史启发式排序，深深感受到了象棋AI的难度
